### PR TITLE
Separating interview methods

### PR DESCRIPTION
**Pull request by pglevy**
This is a draft pull request that addresses issue #58.

I tried to keep the content changes as minimal as possible for now.

These are the things I changed:
- Method titles
- category
- links
- "what" descriptions

Note I also cross-linked them to clarify that each method has a different purpose and focus even though the implementation is largely the same. (We can refine the steps more as needed for each audience later.)

I didn't touch any of the How, Resources, or Considerations content.

image

image

### CODE REVIEW

**Review by allie-shaw — APPROVED** [review]
Looks good to me. :-)

**Comment by sofya-UX** [comment]
Oops, I think I accidentally closed this ☹ I apologies. I meant to close the task of reviewing, but I guess that was the wrong button …

[Bixal]
Sofya Savkina
UX Research Lead
M: 410.800.3396
O: 703.634.5701
E: sofya.savkina@bixal.com
bixal.com<https://www.bixal.com/>

**Comment by pglevy** [comment]
Re-opening to merge changes before closing.

**Review by sofya-UX — APPROVED** [review]

**Comment by pglevy** [comment]
Note to self: content changes related to #74 may cause conflicts when trying to merge.

**Pull request merged**
